/**
 * Single-country SVG download.
 *
 * Builds the SVG via svgBuilder and streams it to the user as an .svg file.
 * No third-party dependency — relies only on Blob + URL.createObjectURL,
 * both of which are safe under our CSP because the URL is generated by the
 * page itself.
 */
import { buildProfileSvg, serializeSvg } from './svgBuilder.js';

function sanitizeFilename(name) {
  // Strip any character that is not alphanumeric, dash, or underscore.
  // Spaces become underscores. This keeps OS-level downloads predictable
  // and avoids any reflected-content / header-injection risk.
  return String(name).trim().replace(/\s+/g, '_').replace(/[^A-Za-z0-9_-]/g, '');
}

/**
 * Trigger a download of the country profile as an .svg file.
 *
 * @param {object} profile - Country data record.
 * @param {string} title - Display title (used in the rendered SVG and filename).
 * @param {number|string} year - Year shown in the SVG.
 */
export function downloadCountrySvg(profile, title, year) {
  const svg = buildProfileSvg(profile, title, year);
  const xml = serializeSvg(svg);
  const blob = new Blob([xml], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const filename = `ROLI_${sanitizeFilename(title)}_${year}.svg`;

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  // Free the object URL after the click has had a chance to register.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
